#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  ./scripts/gen-specs.sh [--target <project-root>] [--project-name <name>] [--force]

Description:
  Generate a baseline specs system for a brand new project under <project-root>/specs.

Options:
  --target <path>       Project root where specs/ will be created (default: current directory)
  --project-name <name> Project display name used in generated markdown (default: basename of target)
  --force               Overwrite existing files generated by this script
  -h, --help            Show this help
EOF
}

TARGET_ROOT="$(pwd)"
PROJECT_NAME=""
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      TARGET_ROOT="${2:-}"
      shift 2
      ;;
    --project-name)
      PROJECT_NAME="${2:-}"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$TARGET_ROOT" ]]; then
  echo "ERROR: --target requires a path." >&2
  exit 1
fi

if [[ ! -d "$TARGET_ROOT" ]]; then
  echo "ERROR: target directory does not exist: $TARGET_ROOT" >&2
  exit 1
fi

if [[ -z "$PROJECT_NAME" ]]; then
  PROJECT_NAME="$(basename "$TARGET_ROOT")"
fi

SPECS_DIR="$TARGET_ROOT/specs"

FILES=(
  "$SPECS_DIR/README.md"
  "$SPECS_DIR/getting-started.md"
  "$SPECS_DIR/design.md"
  "$SPECS_DIR/topology.md"
  "$SPECS_DIR/boundaries.md"
  "$SPECS_DIR/control_planes.md"
  "$SPECS_DIR/services-and-libraries.md"
  "$SPECS_DIR/targets.md"
  "$SPECS_DIR/contracts/control_plane_ownership_matrix.md"
  "$SPECS_DIR/contracts/service_contract.md"
  "$SPECS_DIR/contracts/observability_contract.md"
  "$SPECS_DIR/contracts/security_contract.md"
  "$SPECS_DIR/contracts/data_contract.md"
  "$SPECS_DIR/conformance/scenario_catalog.md"
  "$SPECS_DIR/conformance/spec_conformance_matrix.md"
  "$SPECS_DIR/events/README.md"
  "$SPECS_DIR/events/event_type_catalog.md"
  "$SPECS_DIR/events/widget_event_matrix.md"
  "$SPECS_DIR/events/elm_binding_examples.md"
  "$SPECS_DIR/adr/ADR-0001-control-plane-authority.md"
  "$SPECS_DIR/operations/README.md"
  "$SPECS_DIR/operations/release_governance_and_rollout.md"
  "$SPECS_DIR/operations/ownership_boundary_and_contract_reference.md"
  "$SPECS_DIR/planning/README.md"
)

if [[ "$FORCE" -eq 0 ]]; then
  for file in "${FILES[@]}"; do
    if [[ -e "$file" ]]; then
      echo "ERROR: file exists (use --force to overwrite): $file" >&2
      exit 1
    fi
  done
fi

mkdir -p \
  "$SPECS_DIR/contracts" \
  "$SPECS_DIR/conformance" \
  "$SPECS_DIR/events" \
  "$SPECS_DIR/adr" \
  "$SPECS_DIR/operations" \
  "$SPECS_DIR/planning"

cat > "$SPECS_DIR/README.md" <<EOF
# Specs Index

This directory defines the architecture and governance specification system for \`$PROJECT_NAME\`.

Normative language in this directory uses RFC-2119 terms: **MUST**, **MUST NOT**, **SHOULD**, **SHOULD NOT**, and **MAY**.

## How The Specs System Works

This specs system has five layers:

1. Baseline architecture docs define intent and boundaries:
   - [design.md](design.md)
   - [topology.md](topology.md)
   - [boundaries.md](boundaries.md)
   - [control_planes.md](control_planes.md)
   - [services-and-libraries.md](services-and-libraries.md)
   - [targets.md](targets.md)
2. Contracts define enforceable requirement families (\`REQ-*\`) using normative language.
3. ADRs capture architectural authority and decision history.
4. Conformance maps requirement families to testable scenarios (\`SCN-*\`).
5. Operations/planning docs govern rollout and execution sequencing.

## Traceability Model

- Contracts define requirement IDs: \`REQ-CP-*\`, \`REQ-SVC-*\`, \`REQ-OBS-*\`, \`REQ-SEC-*\`, \`REQ-DATA-*\`.
- Conformance defines scenario IDs: \`SCN-*\`.
- Component specs (added later) define acceptance criteria IDs: \`AC-*\`.
- Every \`AC-*\` MUST map to at least one \`REQ-*\` and at least one \`SCN-*\`.

## Governance Model

Expected change policy:

1. Architecture or contract baseline changes require an ADR update in the same change set.
2. Contract changes require conformance matrix updates in the same change set.
3. AC-bearing component spec changes require:
   - contract updates when behavior changes
   - conformance matrix updates when AC shape changes

## Canonical Baselines

- [design.md](design.md)
- [topology.md](topology.md)
- [boundaries.md](boundaries.md)
- [control_planes.md](control_planes.md)
- [targets.md](targets.md)
- [services-and-libraries.md](services-and-libraries.md)

## Contract Layer

- [contracts/control_plane_ownership_matrix.md](contracts/control_plane_ownership_matrix.md)
- [contracts/service_contract.md](contracts/service_contract.md)
- [contracts/observability_contract.md](contracts/observability_contract.md)
- [contracts/security_contract.md](contracts/security_contract.md)
- [contracts/data_contract.md](contracts/data_contract.md)

## ADRs

- [adr/ADR-0001-control-plane-authority.md](adr/ADR-0001-control-plane-authority.md)

## Conformance

- [conformance/spec_conformance_matrix.md](conformance/spec_conformance_matrix.md)
- [conformance/scenario_catalog.md](conformance/scenario_catalog.md)

## Events

- [events/README.md](events/README.md)
- [events/event_type_catalog.md](events/event_type_catalog.md)
- [events/widget_event_matrix.md](events/widget_event_matrix.md)
- [events/elm_binding_examples.md](events/elm_binding_examples.md)

## Operations

- [operations/README.md](operations/README.md)

## Planning

- [planning/README.md](planning/README.md)

## Start Here

- [getting-started.md](getting-started.md)
EOF

cat > "$SPECS_DIR/getting-started.md" <<'EOF'
# Specs Getting Started

This guide bootstraps a new project using the specs architecture.

## 1) Confirm Baseline Intent

Fill these docs first with concise, high-signal content:

- `design.md`
- `topology.md`
- `boundaries.md`
- `control_planes.md`
- `services-and-libraries.md`
- `targets.md`

Goal: define ownership, major runtime surfaces, and target outcomes before detailed requirements.

## 2) Lock Authority With ADR-0001

Update `adr/ADR-0001-control-plane-authority.md` with:

- authority boundaries
- non-authoritative extension seams
- payload or protocol invariants

This is the architectural tie-breaker when docs conflict.

## 3) Define Initial Contracts

Populate contract requirement sets:

- `contracts/control_plane_ownership_matrix.md`
- `contracts/service_contract.md`
- `contracts/observability_contract.md`
- `contracts/security_contract.md`
- `contracts/data_contract.md`

Use stable IDs (`REQ-*`) and normative statements (`MUST`, `MUST NOT`, `SHOULD`).

## 4) Define Conformance Baseline

Populate:

- `conformance/scenario_catalog.md` with `SCN-*` scenarios
- `conformance/spec_conformance_matrix.md` with mapping:
  - requirement families -> owning contracts -> runtime modules -> scenarios

## 5) Define Event Handling Surface

If the project includes interactive UI surfaces, define:

- `events/event_type_catalog.md`
- `events/widget_event_matrix.md`
- `events/elm_binding_examples.md`

Use Elm handler APIs (`Html.Events`, `Browser.Events`) as the baseline trigger model.

## 6) Add Component Specs Later

When implementation starts, add component specs with acceptance criteria IDs (`AC-*`) and map them to:

- one or more `REQ-*` families
- one or more `SCN-*` scenarios

## 7) Introduce Governance Automation

Add scripts/workflows/hooks to enforce change policy in CI:

- governance validation script
- conformance runner
- PR/push workflows
- pre-commit and pre-push hooks

If you already have those, wire them to fail fast on traceability drift.

## Suggested First Week Sequence

1. Complete baseline docs and ADR-0001.
2. Draft 3-5 requirement families in contracts.
3. Draft event catalog and widget-to-event matrix.
4. Draft 8-12 conformance scenarios.
5. Add governance checks in CI.
6. Start component specs and implementation in parallel.
EOF

cat > "$SPECS_DIR/design.md" <<'EOF'
# Design

## Purpose

Describe the system purpose in one paragraph.

## Core Model

Describe the key runtime model and decision flow.

## Key Constraints

- TODO

## Open Questions

- TODO
EOF

cat > "$SPECS_DIR/topology.md" <<'EOF'
# Topology

## Runtime Surfaces

| Surface | Responsibility | Notes |
|---|---|---|
| `TODO` | `TODO` | `TODO` |

## Data/Control Flow

Describe high-level directional flow between surfaces.
EOF

cat > "$SPECS_DIR/boundaries.md" <<'EOF'
# Boundaries

## Inbound Boundaries

- TODO

## Outbound Boundaries

- TODO

## Trust/Failure Boundaries

- TODO
EOF

cat > "$SPECS_DIR/control_planes.md" <<'EOF'
# Control Planes

| Plane | Authority | Non-Authority |
|---|---|---|
| `ui` | `TODO` | `TODO` |
| `transport` | `TODO` | `TODO` |
| `runtime` | `TODO` | `TODO` |
EOF

cat > "$SPECS_DIR/services-and-libraries.md" <<'EOF'
# Services and Libraries

## Planned Runtime Modules

| Module | Responsibility | Ownership |
|---|---|---|
| `TODO.Module` | `TODO` | `TODO` |

## External Libraries

| Library | Role |
|---|---|
| `TODO` | `TODO` |

## Contract Alignment

The planned runtime modules MUST align with:

- [contracts/control_plane_ownership_matrix.md](contracts/control_plane_ownership_matrix.md)
- [contracts/service_contract.md](contracts/service_contract.md)
- [contracts/observability_contract.md](contracts/observability_contract.md)
- [contracts/security_contract.md](contracts/security_contract.md)
- [contracts/data_contract.md](contracts/data_contract.md)
EOF

cat > "$SPECS_DIR/targets.md" <<'EOF'
# Targets

## Product/Runtime Targets

| Target | Description | Measurement |
|---|---|---|
| `TGT-001` | `TODO` | `TODO` |

## Non-Targets

- TODO
EOF

cat > "$SPECS_DIR/contracts/control_plane_ownership_matrix.md" <<'EOF'
# Control Plane Ownership Matrix

## Requirement Set

- `REQ-CP-001`: Every covered module MUST map to exactly one primary control plane.
- `REQ-CP-002`: Ownership conflicts across docs MUST resolve in favor of this matrix and ADR-0001.
- `REQ-CP-003`: Transport modules MUST NOT become domain-state authorities.
- `REQ-CP-004`: Ownership changes MUST update this matrix in the same change set.
- `REQ-CP-005`: New runtime modules MUST be assigned before merge.

## Ownership Matrix

| Runtime Module | Primary Plane | Notes |
|---|---|---|
| `TODO.Module` | `TODO` | `TODO` |

## ADR References

- [../adr/ADR-0001-control-plane-authority.md](../adr/ADR-0001-control-plane-authority.md)
EOF

cat > "$SPECS_DIR/contracts/service_contract.md" <<'EOF'
# Service Contract

## Requirement Set

- `REQ-SVC-001`: Runtime modules MUST expose explicit responsibilities and stable API surfaces.
- `REQ-SVC-002`: Ingress/egress operations MUST preserve correlation continuity.
- `REQ-SVC-003`: Ingress payloads MUST be validated before dispatch.
- `REQ-SVC-004`: Runtime failures MUST return typed errors.
- `REQ-SVC-005`: Service operations MUST emit required observability events.

## Key Types

```text
RuntimeContext { correlation_id: string, request_id: string, ... }
TypedError { error_code: string, category: string, retryable: boolean, details?: map }
```

## ADR References

- [../adr/ADR-0001-control-plane-authority.md](../adr/ADR-0001-control-plane-authority.md)
EOF

cat > "$SPECS_DIR/contracts/observability_contract.md" <<'EOF'
# Observability Contract

## Requirement Set

- `REQ-OBS-001`: Runtime operations MUST emit structured events for success and failure paths.
- `REQ-OBS-002`: Events MUST include join keys (`correlation_id`, `request_id`) where applicable.
- `REQ-OBS-003`: Error events MUST carry typed error metadata.
- `REQ-OBS-004`: Metrics families MUST cover latency, throughput, and failures.
- `REQ-OBS-005`: Observability schemas MUST be versioned.

## Required Event Families

- `runtime.operation.started.v1`
- `runtime.operation.completed.v1`
- `runtime.operation.failed.v1`
EOF

cat > "$SPECS_DIR/contracts/security_contract.md" <<'EOF'
# Security Contract

## Requirement Set

- `REQ-SEC-001`: Authentication state MUST be validated at trusted ingress boundaries.
- `REQ-SEC-002`: Authorization decisions MUST be explicit and auditable.
- `REQ-SEC-003`: Sensitive fields MUST be redacted from logs and telemetry.
- `REQ-SEC-004`: Security-relevant failures MUST fail closed by default.
- `REQ-SEC-005`: Security policy updates MUST be versioned and traceable.

## Notes

Document threat-model and policy references here.
EOF

cat > "$SPECS_DIR/contracts/data_contract.md" <<'EOF'
# Data Contract

## Requirement Set

- `REQ-DATA-001`: External and internal payload schemas MUST be explicit and versioned.
- `REQ-DATA-002`: Schema-breaking changes MUST require migration and compatibility strategy.
- `REQ-DATA-003`: Validation failures MUST return typed errors.
- `REQ-DATA-004`: Data ownership and mutation authority MUST be explicit.
- `REQ-DATA-005`: Persistence and replay boundaries MUST be documented when applicable.

## Schema Inventory

| Schema | Version | Owner | Notes |
|---|---|---|---|
| `TODO` | `v1` | `TODO` | `TODO` |
EOF

cat > "$SPECS_DIR/conformance/scenario_catalog.md" <<'EOF'
# Scenario Catalog

Canonical validation scenarios for baseline contract conformance.

| Scenario ID | Name | Summary |
|---|---|---|
| `SCN-001` | Control-plane ownership consistency | Runtime modules map to one canonical plane without conflicts. |
| `SCN-002` | Ingress validation behavior | Malformed ingress payloads fail closed with typed errors. |
| `SCN-003` | Correlation continuity | Correlation/request IDs are preserved through core runtime flows. |
| `SCN-004` | Typed error normalization | Runtime failures return normalized typed errors. |
| `SCN-005` | Observability minimum baseline | Required events and metrics families are emitted. |
| `SCN-006` | Authorization enforcement | Unauthorized actions are denied with auditable outcomes. |
| `SCN-007` | Sensitive data redaction | Telemetry/log outputs avoid leaking sensitive fields. |
| `SCN-008` | Data schema compatibility | Versioned payloads satisfy validation and compatibility rules. |
EOF

cat > "$SPECS_DIR/conformance/spec_conformance_matrix.md" <<'EOF'
# Spec Conformance Matrix

This matrix maps requirement families to owning contracts and canonical baseline scenarios.

| Requirement Family | Owning Contract | Primary Runtime Modules | Scenario Coverage |
|---|---|---|---|
| `REQ-CP-001`..`REQ-CP-005` | [../contracts/control_plane_ownership_matrix.md](../contracts/control_plane_ownership_matrix.md) | `TODO.Module` | `SCN-001` |
| `REQ-SVC-001`..`REQ-SVC-005` | [../contracts/service_contract.md](../contracts/service_contract.md) | `TODO.Module` | `SCN-002`, `SCN-003`, `SCN-004` |
| `REQ-OBS-001`..`REQ-OBS-005` | [../contracts/observability_contract.md](../contracts/observability_contract.md) | `TODO.Module` | `SCN-003`, `SCN-005` |
| `REQ-SEC-001`..`REQ-SEC-005` | [../contracts/security_contract.md](../contracts/security_contract.md) | `TODO.Module` | `SCN-006`, `SCN-007` |
| `REQ-DATA-001`..`REQ-DATA-005` | [../contracts/data_contract.md](../contracts/data_contract.md) | `TODO.Module` | `SCN-008` |

## Acceptance Mapping Rule

Every future AC-bearing component spec MUST map to at least one `REQ-*` family and one `SCN-*` scenario.
EOF

cat > "$SPECS_DIR/events/README.md" <<'EOF'
# Widget Event Specs

This directory defines widget interaction events that code handlers should process.

## Scope

1. Canonical event type names and payload conventions.
2. Widget-to-event mapping for the built-in catalog.
3. Elm binding examples (`Html.Events` and `Browser.Events`).

## Documents

- [event_type_catalog.md](event_type_catalog.md)
- [widget_event_matrix.md](widget_event_matrix.md)
- [elm_binding_examples.md](elm_binding_examples.md)
EOF

cat > "$SPECS_DIR/events/event_type_catalog.md" <<'EOF'
# Event Type Catalog

## Envelope Shape

```text
WidgetUiEvent {
  type: string,
  widget_id: string,
  widget_kind: string,
  correlation_id: string,
  request_id: string,
  timestamp: string,
  data: map
}
```

## Baseline Event Types

| Event Type | Typical Elm Binding | Required `data` Keys |
|---|---|---|
| `unified.button.clicked` | `Html.Events.onClick` | `action` or `button_id` or `widget_id` |
| `unified.input.changed` | `Html.Events.onInput`, `Html.Events.onCheck` | `value` plus `input_id` or `widget_id` |
| `unified.form.submitted` | `Html.Events.onSubmit` | `form_id` or `widget_id` |
| `unified.element.focused` | `Html.Events.onFocus` | `widget_id` |
| `unified.element.blurred` | `Html.Events.onBlur` | `widget_id` |
| `unified.item.selected` | `onClick` / keyboard handlers | `widget_id` plus `item_id` or `index` |

## Extended Event Types

| Event Type | Required `data` Keys |
|---|---|
| `unified.item.toggled` | `widget_id`, `selected` plus `item_id` or `index` |
| `unified.menu.action_selected` | `widget_id`, `action_id` |
| `unified.table.row_selected` | `widget_id`, `row_index` |
| `unified.table.sorted` | `widget_id`, `column`, `direction` |
| `unified.tab.changed` | `widget_id`, `tab_id` |
| `unified.tree.node_selected` | `widget_id`, `node_id` |
| `unified.tree.node_toggled` | `widget_id`, `node_id`, `expanded` |
| `unified.overlay.confirmed` | `widget_id`, `action_id` |
| `unified.overlay.closed` | `widget_id`, optional `reason` |
| `unified.scroll.changed` | `widget_id`, `position` |
| `unified.viewport.resized` | `widget_id`, `width`, `height` |

## Elm Notes

1. `onInput` reads `event.target.value` and stops propagation.
2. `onCheck` reads `event.target.checked`.
3. `onSubmit` prevents default browser submit navigation.
4. Keyboard and pointer details require custom decoders with `Html.Events.on`.
5. Global resize/visibility/drag interactions use `Browser.Events`.
EOF

cat > "$SPECS_DIR/events/widget_event_matrix.md" <<'EOF'
# Widget Event Matrix

Widget-to-event baseline for built-in catalog coverage.

| Widget ID | Standard Event Types |
|---|---|
| `block` | None |
| `button` | `unified.button.clicked` |
| `label` | None |
| `list` | `unified.item.selected`, `unified.item.toggled` |
| `pick_list` | `unified.item.selected`, `unified.overlay.closed` |
| `progress` | None |
| `text_input_primitive` | `unified.input.changed`, `unified.form.submitted` |
| `alert_dialog` | `unified.overlay.confirmed`, `unified.overlay.closed` |
| `bar_chart` | `unified.chart.point_selected` (optional) |
| `canvas` | `unified.canvas.pointer.changed` |
| `cluster_dashboard` | `unified.item.selected`, `unified.view.changed` |
| `command_palette` | `unified.input.changed`, `unified.command.executed`, `unified.overlay.closed` |
| `context_menu` | `unified.menu.action_selected`, `unified.overlay.closed` |
| `dialog` | `unified.overlay.confirmed`, `unified.overlay.closed` |
| `form_builder` | `unified.input.changed`, `unified.form.submitted`, `unified.item.toggled` |
| `gauge` | None |
| `line_chart` | `unified.chart.point_selected` (optional) |
| `log_viewer` | `unified.scroll.changed`, `unified.item.selected` |
| `markdown_viewer` | `unified.link.clicked` (optional) |
| `menu` | `unified.menu.action_selected` |
| `process_monitor` | `unified.item.selected`, `unified.action.requested` |
| `scroll_bar` | `unified.scroll.changed` |
| `sparkline` | `unified.chart.point_selected` (optional) |
| `split_pane` | `unified.split.resized`, `unified.split.collapse_changed` |
| `stream_widget` | `unified.item.selected` (optional) |
| `supervision_tree_viewer` | `unified.tree.node_selected`, `unified.tree.node_toggled` |
| `table` | `unified.table.row_selected`, `unified.table.sorted` |
| `tabs` | `unified.tab.changed` |
| `text_input` | `unified.input.changed`, `unified.form.submitted` |
| `toast` | `unified.toast.dismissed` |
| `toast_manager` | `unified.toast.dismissed`, `unified.toast.cleared` |
| `tree_view` | `unified.tree.node_selected`, `unified.tree.node_toggled` |
| `viewport` | `unified.scroll.changed`, `unified.viewport.resized` |
EOF

cat > "$SPECS_DIR/events/elm_binding_examples.md" <<'EOF'
# Elm Binding Examples

```elm
type Msg
    = WidgetEvent { eventType : String, widgetId : String, data : Json.Encode.Value }
```

```elm
Html.button
    [ Html.Events.onClick
        (WidgetEvent
            { eventType = "unified.button.clicked"
            , widgetId = "save_button"
            , data = Json.Encode.object [ ( "action", Json.Encode.string "save" ) ]
            }
        )
    ]
    [ Html.text "Save" ]
```

```elm
Html.input
    [ Html.Events.onInput
        (\value ->
            WidgetEvent
                { eventType = "unified.input.changed"
                , widgetId = "search_input"
                , data = Json.Encode.object [ ( "value", Json.Encode.string value ) ]
                }
        )
    ]
    []
```

```elm
subscriptions : model -> Sub Msg
subscriptions _ =
    Browser.Events.onResize
        (\w h ->
            WidgetEvent
                { eventType = "unified.viewport.resized"
                , widgetId = "main_viewport"
                , data =
                    Json.Encode.object
                        [ ( "width", Json.Encode.int w )
                        , ( "height", Json.Encode.int h )
                        ]
                }
        )
```
EOF

cat > "$SPECS_DIR/adr/ADR-0001-control-plane-authority.md" <<'EOF'
# ADR-0001: Control-Plane Authority

## Status

Accepted

## Context

Describe why explicit authority boundaries are needed.

## Decision

1. UI-plane authority: `TODO`
2. Transport-plane authority: `TODO`
3. Runtime/domain authority: `TODO`
4. Non-authoritative extension seams: `TODO`

## Consequences

- Ownership boundaries are explicit and reviewable.
- Contract and conformance docs can enforce one control-plane model.

## Related Requirements

- `REQ-CP-001` through `REQ-CP-005`
- `REQ-SVC-001` through `REQ-SVC-005`
- `REQ-OBS-001` through `REQ-OBS-005`
- `REQ-SEC-001` through `REQ-SEC-005`
- `REQ-DATA-001` through `REQ-DATA-005`
EOF

cat > "$SPECS_DIR/operations/README.md" <<'EOF'
# Operations Specs

Operational governance and rollout references.

- [release_governance_and_rollout.md](release_governance_and_rollout.md)
- [ownership_boundary_and_contract_reference.md](ownership_boundary_and_contract_reference.md)
EOF

cat > "$SPECS_DIR/operations/release_governance_and_rollout.md" <<'EOF'
# Release Governance And Rollout

## Purpose

Define release gates tied to contracts, conformance, and ADR updates.

## Release Gates

1. Contract deltas reviewed and traceability updated.
2. Conformance matrix/scenarios aligned.
3. ADR updates included for baseline authority shifts.

## Rollout Checklist

- TODO
EOF

cat > "$SPECS_DIR/operations/ownership_boundary_and_contract_reference.md" <<'EOF'
# Ownership Boundary And Contract Reference

## Purpose

Operational quick-reference for control-plane ownership and contract authorities.

## References

- [../control_planes.md](../control_planes.md)
- [../contracts/control_plane_ownership_matrix.md](../contracts/control_plane_ownership_matrix.md)
- [../adr/ADR-0001-control-plane-authority.md](../adr/ADR-0001-control-plane-authority.md)
EOF

cat > "$SPECS_DIR/planning/README.md" <<'EOF'
# Planning Specs

Use this directory for phased delivery planning once contracts and conformance baselines are established.
EOF

echo "Generated baseline specs scaffold for '$PROJECT_NAME' in:"
echo "  $SPECS_DIR"
echo
echo "Next step:"
echo "  Open $SPECS_DIR/getting-started.md"
