defmodule WebUi.Iur.InterpreterTest do
  use ExUnit.Case, async: true

  alias WebUi.Iur.Interpreter
  alias WebUi.TypedError

  test "interprets nested vbox/hbox trees with deterministic ids and widget inventory" do
    spec = %{
      type: :vbox,
      id: :root_layout,
      spacing: 2,
      children: [
        %{
          type: :button,
          id: :save_button,
          label: "Save",
          on_click: :save
        },
        %{
          type: :hbox,
          children: [
            %{
              type: :text_input,
              id: :name_input,
              value: "",
              on_change: :name_changed,
              on_submit: {:submit_name, %{source: "profile_form"}}
            }
          ]
        }
      ]
    }

    assert {:ok, interpreted} = Interpreter.interpret(spec, correlation_id: "corr-iur-001")
    assert interpreted.root.type == :layout
    assert interpreted.root.kind == "vbox"
    assert interpreted.root.id == "root_layout"
    assert interpreted.root.props.spacing == 2

    assert Enum.map(interpreted.widgets, & &1.widget_id) == ["save_button", "name_input"]
    assert Enum.map(interpreted.widgets, & &1.widget_kind) == ["button", "text_input"]

    assert Enum.map(interpreted.signals, & &1.source_field) == [
             "on_click",
             "on_change",
             "on_submit"
           ]

    assert Enum.map(interpreted.signals, & &1.widget_id) == [
             "save_button",
             "name_input",
             "name_input"
           ]

    assert Enum.map(interpreted.events, & &1.type) == [
             "unified.button.clicked",
             "unified.input.changed",
             "unified.form.submitted"
           ]

    assert Enum.at(interpreted.events, 0).data.action == "save"
    assert Enum.at(interpreted.events, 1).data.widget_id == "name_input"
    assert Enum.at(interpreted.events, 2).data.action == "submit_name"
  end

  test "supports map inputs with string keys and autogenerated ids" do
    spec = %{
      "type" => "hbox",
      "children" => [
        %{"type" => "text", "content" => "Hello"},
        %{"type" => "button", "label" => "Run", "on_click" => %{"action" => "run"}}
      ]
    }

    assert {:ok, interpreted} = Interpreter.interpret(spec)

    assert interpreted.root.id == "hbox_root"
    assert Enum.map(interpreted.widgets, & &1.widget_kind) == ["label", "button"]
    assert Enum.map(interpreted.widgets, & &1.widget_id) == ["text_0", "button_1"]
    assert length(interpreted.signals) == 1
    assert Enum.map(interpreted.events, & &1.type) == ["unified.button.clicked"]
    assert hd(interpreted.events).data.action == "run"
  end

  test "maps atom, map, and tuple signals into canonical event payloads" do
    spec = %{
      type: :vbox,
      children: [
        %{type: :button, id: :run_button, on_click: :run},
        %{type: :button, id: :stop_button, on_click: %{"action" => "stop"}},
        %{type: :text_input, id: :query_input, on_submit: {:search, %{source: "header"}}}
      ]
    }

    assert {:ok, interpreted} = Interpreter.interpret(spec)

    assert Enum.map(interpreted.events, & &1.type) == [
             "unified.button.clicked",
             "unified.button.clicked",
             "unified.form.submitted"
           ]

    assert Enum.at(interpreted.events, 0).data.action == "run"
    assert Enum.at(interpreted.events, 1).data.action == "stop"
    assert Enum.at(interpreted.events, 2).data.action == "search"
    assert Enum.at(interpreted.events, 2).data.form_id == "query_input"
  end

  test "fails closed when layout children are not a list" do
    spec = %{type: :vbox, id: :invalid_layout, children: %{type: :button}}

    assert {:error, %TypedError{} = error} =
             Interpreter.interpret(spec, correlation_id: "corr-iur-002")

    assert error.error_code == "iur.interpreter.invalid_children"
    assert error.correlation_id == "corr-iur-002"
  end

  test "fails closed when element type cannot be inferred" do
    spec = %{id: :missing_type}

    assert {:error, %TypedError{} = error} = Interpreter.interpret(spec)
    assert error.error_code == "iur.interpreter.unknown_element_type"
  end
end
