defmodule WebUi.Iur.InterpreterTest do
  use ExUnit.Case, async: true

  alias WebUi.Iur.Interpreter
  alias WebUi.TypedError

  test "interprets nested vbox/hbox trees with deterministic ids and widget inventory" do
    spec = %{
      type: :vbox,
      id: :root_layout,
      spacing: 2,
      children: [
        %{
          type: :button,
          id: :save_button,
          label: "Save",
          on_click: :save
        },
        %{
          type: :hbox,
          children: [
            %{
              type: :text_input,
              id: :name_input,
              value: "",
              on_change: :name_changed,
              on_submit: {:submit_name, %{source: "profile_form"}}
            }
          ]
        }
      ]
    }

    assert {:ok, interpreted} = Interpreter.interpret(spec, correlation_id: "corr-iur-001")
    assert interpreted.root.type == :layout
    assert interpreted.root.kind == "vbox"
    assert interpreted.root.id == "root_layout"
    assert interpreted.root.props.spacing == 2

    assert Enum.map(interpreted.widgets, & &1.widget_id) == ["save_button", "name_input"]
    assert Enum.map(interpreted.widgets, & &1.widget_kind) == ["button", "text_input"]

    assert Enum.map(interpreted.signals, & &1.source_field) == [
             "on_click",
             "on_change",
             "on_submit"
           ]

    assert Enum.map(interpreted.signals, & &1.widget_id) == [
             "save_button",
             "name_input",
             "name_input"
           ]
  end

  test "supports map inputs with string keys and autogenerated ids" do
    spec = %{
      "type" => "hbox",
      "children" => [
        %{"type" => "text", "content" => "Hello"},
        %{"type" => "button", "label" => "Run", "on_click" => %{"action" => "run"}}
      ]
    }

    assert {:ok, interpreted} = Interpreter.interpret(spec)

    assert interpreted.root.id == "hbox_root"
    assert Enum.map(interpreted.widgets, & &1.widget_kind) == ["label", "button"]
    assert Enum.map(interpreted.widgets, & &1.widget_id) == ["text_0", "button_1"]
    assert length(interpreted.signals) == 1
  end

  test "fails closed when layout children are not a list" do
    spec = %{type: :vbox, id: :invalid_layout, children: %{type: :button}}

    assert {:error, %TypedError{} = error} =
             Interpreter.interpret(spec, correlation_id: "corr-iur-002")

    assert error.error_code == "iur.interpreter.invalid_children"
    assert error.correlation_id == "corr-iur-002"
  end

  test "fails closed when element type cannot be inferred" do
    spec = %{id: :missing_type}

    assert {:error, %TypedError{} = error} = Interpreter.interpret(spec)
    assert error.error_code == "iur.interpreter.unknown_element_type"
  end
end
